"""
AgentForge Constants & Enumerations.
Central definition of all shared enums used across the platform.
"""

from enum import Enum


class ProjectType(str, Enum):
    """Types of software projects AgentForge can build."""
    WEB_APP = "web_app"
    MOBILE_APP = "mobile_app"
    API_SERVICE = "api_service"
    CLI_TOOL = "cli_tool"
    DATA_PIPELINE = "data_pipeline"
    ML_MODEL = "ml_model"
    MICROSERVICE = "microservice"
    FULL_STACK = "full_stack"
    SAAS_PLATFORM = "saas_platform"
    ECOMMERCE = "ecommerce"


class TechStack(str, Enum):
    """Supported technology stacks."""
    # Backend
    PYTHON_FASTAPI = "python_fastapi"
    PYTHON_DJANGO = "python_django"
    PYTHON_FLASK = "python_flask"
    NODE_EXPRESS = "node_express"
    NODE_NESTJS = "node_nestjs"
    GO_GIN = "go_gin"
    JAVA_SPRING = "java_spring"
    # Frontend
    REACT = "react"
    VUE = "vue"
    NEXTJS = "nextjs"
    ANGULAR = "angular"
    SVELTE = "svelte"
    # Database
    POSTGRESQL = "postgresql"
    MYSQL = "mysql"
    MONGODB = "mongodb"
    SQLITE = "sqlite"
    REDIS = "redis"
    # Full stacks
    MERN = "mern"  # MongoDB + Express + React + Node
    MEAN = "mean"  # MongoDB + Express + Angular + Node
    PERN = "pern"  # PostgreSQL + Express + React + Node
    DJANGO_REACT = "django_react"
    FASTAPI_REACT = "fastapi_react"


class AgentRole(str, Enum):
    """The 7 specialized AgentForge agents."""
    PRODUCT_MANAGER = "product_manager"
    SOLUTION_ARCHITECT = "solution_architect"
    DEVELOPER = "developer"
    QA_ENGINEER = "qa_engineer"
    DOCUMENTATION = "documentation"
    DEVOPS = "devops"
    PPT = "ppt"


class ProjectStatus(str, Enum):
    """Lifecycle states of a project."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    AGENT_RUNNING = "agent_running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class OutputType(str, Enum):
    """Types of files generated by agents."""
    BRD = "brd"
    SRS = "srs"
    RISK_MATRIX = "risk_matrix"
    MILESTONES = "milestones"
    ARCHITECTURE = "architecture"
    DATABASE_SCHEMA = "database_schema"
    API_SPEC = "api_spec"
    TECH_STACK = "tech_stack"
    SOURCE_CODE = "source_code"
    FOLDER_STRUCTURE = "folder_structure"
    TEST_PLAN = "test_plan"
    UNIT_TESTS = "unit_tests"
    INTEGRATION_TESTS = "integration_tests"
    CODE_QUALITY = "code_quality"
    README = "readme"
    SETUP_GUIDE = "setup_guide"
    API_DOCS = "api_docs"
    DEPLOYMENT_GUIDE = "deployment_guide"
    DOCKERFILE = "dockerfile"
    DOCKER_COMPOSE = "docker_compose"
    CICD_PIPELINE = "cicd_pipeline"
    K8S_MANIFESTS = "k8s_manifests"
    DEPLOY_SCRIPTS = "deploy_scripts"
    PITCH_DECK = "pitch_deck"
    HACKATHON_DECK = "hackathon_deck"
    INVESTOR_DECK = "investor_deck"


class UserRole(str, Enum):
    """RBAC user roles."""
    ADMIN = "admin"
    USER = "user"
    VIEWER = "viewer"


class LogLevel(str, Enum):
    """Log severity levels."""
    DEBUG = "debug"
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


# Agent execution order in the pipeline DAG
PIPELINE_ORDER: list[AgentRole] = [
    AgentRole.PRODUCT_MANAGER,
    AgentRole.SOLUTION_ARCHITECT,
    AgentRole.DEVELOPER,
    AgentRole.QA_ENGINEER,
    AgentRole.DOCUMENTATION,
    AgentRole.DEVOPS,
    AgentRole.PPT,
]

# Token pricing per model (USD per 1K tokens)
MODEL_PRICING: dict[str, dict[str, float]] = {
    "gpt-4o": {"input": 0.005, "output": 0.015},
    "gpt-4-turbo": {"input": 0.01, "output": 0.03},
    "gpt-4": {"input": 0.03, "output": 0.06},
    "gpt-3.5-turbo": {"input": 0.0005, "output": 0.0015},
    "claude-3-5-sonnet-20241022": {"input": 0.003, "output": 0.015},
    "claude-3-opus-20240229": {"input": 0.015, "output": 0.075},
    "gemini-1.5-pro": {"input": 0.00125, "output": 0.005},
    "default": {"input": 0.01, "output": 0.03},
}

# Maximum tokens for context injection via RAG
MAX_CONTEXT_TOKENS = 4096

# Default budget in USD
DEFAULT_BUDGET_USD = 5.0

# WebSocket event types
WS_EVENT_AGENT_START = "agent_start"
WS_EVENT_AGENT_PROGRESS = "agent_progress"
WS_EVENT_AGENT_COMPLETE = "agent_complete"
WS_EVENT_AGENT_ERROR = "agent_error"
WS_EVENT_PIPELINE_COMPLETE = "pipeline_complete"
WS_EVENT_FILE_GENERATED = "file_generated"
